name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod 

      - uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }} # <- Use the same env variable just right here
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Read .env
        id: hugo-version
        run: |
          . ./.env
          echo "HUGO_VERSION=${HUGO_VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'
          extended: true
          
      - name: Build
        run: hugo --minify 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main 
          external_repository: lwmfjc/lwmfjc.github.io 
        # with:
        #   github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        #   publish_dir: ./public